apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 25
  labels:
    app: childgen-python
  name: childgen-python
  namespace: default
  resourceVersion: "26272"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/childgen-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: childgen-python
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: childgen-python
    spec:
      containers:
      - image: telexine/telexine/keras-childgen:latest
        imagePullPolicy: Always
        name: telexine/keras-childgen
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 25
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: childgen-python
  name: childgen-python
  namespace: default
  resourceVersion: "1139"
  selfLink: /api/v1/namespaces/default/services/childgen-python
spec:
  clusterIP: 10.96.0.22
  externalTrafficPolicy: Cluster
  ports:
  - name: 5000-to-5000-tcp
    nodePort: 31527
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: childgen-python
  sessionAffinity: None
  type: LoadBalancer
